name: Java auto build with Gradle

on: [push,workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
          java-package: jdk
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle, using shadowJar
        run: ./gradlew clean shadowJar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: BungeeSK
          path: build/libs/**
